"""Write outputs to disk + JSON sidecar. Schema lives in DATABASE.md."""
from __future__ import annotations

import io
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from PIL import Image

from aquarender import __version__
from aquarender.params import ResolvedParams
from aquarender.types import EngineType


@dataclass(slots=True)
class EngineContext:
    session_id: str
    engine_type: EngineType
    gpu_name: str | None
    comfyui_version: str | None
    tunnel_url: str


@dataclass(slots=True)
class WrittenOutput:
    output_path: Path
    sidecar_path: Path
    width: int
    height: int
    file_size_bytes: int


class MetadataWriter:
    """Persists generated bytes + a sibling .json sidecar.

    Layout: <outputs_dir>/<YYYY-MM-DD>/<stem>_watercolor.png (and .json).
    Batch outputs go under <outputs_dir>/<batch_id>/ instead of a date folder.
    """

    METADATA_VERSION = 2

    def __init__(self, outputs_dir: Path) -> None:
        self._outputs_dir = outputs_dir

    def write(
        self,
        *,
        job_id: str,
        batch_id: str | None,
        preset_id: str,
        preset_name: str,
        input_path: Path | str,
        input_filename: str,
        output_bytes: bytes,
        params: ResolvedParams,
        seed: int,
        duration_ms: int,
        engine: EngineContext,
        status: str = "success",
    ) -> WrittenOutput:
        target_dir = (
            (self._outputs_dir / batch_id)
            if batch_id
            else (self._outputs_dir / datetime.now(UTC).strftime("%Y-%m-%d"))
        )
        target_dir.mkdir(parents=True, exist_ok=True)

        stem = Path(input_filename).stem
        ext = "png" if params.output.format == "png" else "webp"
        output_path = _unique_path(target_dir / f"{stem}_watercolor.{ext}")
        sidecar_path = output_path.with_suffix(".json")

        output_path.write_bytes(output_bytes)

        # Inspect dimensions from the bytes we just wrote
        with Image.open(io.BytesIO(output_bytes)) as im:
            width, height = im.size

        sidecar: dict[str, Any] = {
            "metadata_version": self.METADATA_VERSION,
            "input_file": input_filename,
            "input_path": str(input_path),
            "output_file": output_path.name,
            "output_path": str(output_path),
            "preset_id": preset_id,
            "preset_name": preset_name,
            "params": params.model_dump(),
            "seed": seed,
            "duration_ms": duration_ms,
            "width": width,
            "height": height,
            "file_size_bytes": output_path.stat().st_size,
            "job_id": job_id,
            "batch_id": batch_id,
            "engine": {
                "session_id": engine.session_id,
                "type": engine.engine_type,
                "gpu": engine.gpu_name,
                "comfyui_version": engine.comfyui_version,
                "tunnel_url_at_time": engine.tunnel_url,
            },
            "aquarender_version": __version__,
            "created_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "status": status,
        }
        sidecar_path.write_text(json.dumps(sidecar, indent=2, sort_keys=True))

        return WrittenOutput(
            output_path=output_path,
            sidecar_path=sidecar_path,
            width=width,
            height=height,
            file_size_bytes=output_path.stat().st_size,
        )


def _unique_path(path: Path) -> Path:
    """Avoid clobbering when filenames collide."""
    if not path.exists():
        return path
    stem, suffix = path.stem, path.suffix
    parent = path.parent
    n = 2
    while True:
        candidate = parent / f"{stem}_{n}{suffix}"
        if not candidate.exists():
            return candidate
        n += 1
